// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_secret::Resource::new(&ctx, "res", pulumi_secret::ResourceArgs { private: Some(pulumi::ops::to_string(pulumi::pv::string("closed")).cast()), private_array: Some(pulumi::pv::array(vec![pulumi::ops::to_string(pulumi::pv::string("closed"))]).cast()), private_data: Some(pulumi_secret::types::DataArgs { private: Some(pulumi::ops::to_string(pulumi::pv::string("closed")).cast()), public: Some(pulumi::ops::to_string(pulumi::pv::string("open")).cast()) }), private_data_array: Some(vec![pulumi_secret::types::DataArgs { private: Some(pulumi::ops::to_string(pulumi::pv::string("closed")).cast()), public: Some(pulumi::ops::to_string(pulumi::pv::string("open")).cast()) }]), private_data_map: Some(std::collections::BTreeMap::from([("key".to_string(), pulumi_secret::types::DataArgs { private: Some(pulumi::ops::to_string(pulumi::pv::string("closed")).cast()), public: Some(pulumi::ops::to_string(pulumi::pv::string("open")).cast()) })])), private_map: Some(pulumi::pv::object(vec![("key".to_string(), pulumi::ops::to_string(pulumi::pv::string("closed")))]).cast()), public: Some(pulumi::ops::to_string(pulumi::pv::string("open")).cast()), public_data: Some(pulumi_secret::types::DataArgs { private: Some(pulumi::ops::to_string(pulumi::pv::string("closed")).cast()), public: Some(pulumi::ops::to_string(pulumi::pv::string("open")).cast()) }) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
