// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let replacement_trigger = pulumi_simple::Resource::new(&ctx, "replacementTrigger", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { replacement_trigger: Some(pulumi::pv::string("test")), ..Default::default() });
        let unknown = pulumi_output::Resource::new(&ctx, "unknown", pulumi_output::ResourceArgs { value: Some(pulumi::ops::to_number(pulumi::pv::number(1.0)).cast()) }, pulumi::ResourceOptions::default());
        let unknown_replacement_trigger = pulumi_simple::Resource::new(&ctx, "unknownReplacementTrigger", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { replacement_trigger: Some(pulumi::pv::string("hellohello")), ..Default::default() });
        let not_replacement_trigger = pulumi_simple::Resource::new(&ctx, "notReplacementTrigger", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let secret_replacement_trigger = pulumi_simple::Resource::new(&ctx, "secretReplacementTrigger", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { replacement_trigger: Some(pulumi::pv::secret(pulumi::pv::array(vec![pulumi::pv::number(1.0), pulumi::pv::number(2.0), pulumi::pv::number(3.0)]))), ..Default::default() });
        Ok(())
    });
}
