[package]
name = "l2-namespaced-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
pulumi = { path = "ROOT/artifacts/pulumi-0.1.0" }
pulumi_component = { path = "ROOT/artifacts/pulumi_component-13.3.7" }
pulumi_namespaced = { path = "ROOT/artifacts/pulumi_namespaced-16.0.0" }

[workspace]
