// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ConfigurerArgs {
    pub provider_config: pulumi::Output<String>,
}

impl ConfigurerArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.provider_config;
            inputs.push(("providerConfig".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Configurer {
    resource: pulumi::Resource,
}

impl Configurer {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ConfigurerArgs, options: pulumi::ResourceOptions) -> Configurer {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "configurer:index:Configurer".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "38.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Configurer { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn provider_config(&self) -> pulumi::Output<String> {
        self.resource.output("providerConfig").cast()
    }
}

#[derive(Clone, Debug)]
pub struct CustomArgs {
    pub value: pulumi::Output<String>,
}

impl CustomArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Custom {
    resource: pulumi::Resource,
}

impl Custom {
    pub fn new(ctx: &pulumi::Context, name: &str, args: CustomArgs, options: pulumi::ResourceOptions) -> Custom {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "configurer:index:Custom".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "38.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Custom { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn config(&self) -> pulumi::Output<String> {
        self.resource.output("config").cast()
    }

    pub fn value(&self) -> pulumi::Output<String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ProviderArgs {
    pub config: pulumi::Output<String>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.config;
            inputs.push(("config".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:configurer".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "38.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn config(&self) -> pulumi::Output<String> {
        self.resource.output("config").cast()
    }
}

