// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let default_res = pulumi_call::Custom::new(&ctx, "defaultRes", pulumi_call::CustomArgs { value: Some(pulumi::ops::to_string(pulumi::pv::string("defaultValue")).cast()) }, pulumi::ResourceOptions::default());
        ctx.export("defaultProviderValue", ctx.call("call:index:Custom/providerValue", default_res.pulumi_resource(), vec![]).index("result"));
        Ok(())
    });
}
