// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub text: pulumi::Output<String>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.text;
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "config:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "9.0.0".to_string(),
            plugin_download_url: "http://example.com".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn text(&self) -> pulumi::Output<String> {
        self.resource.output("text").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ProviderArgs {
    pub name: pulumi::Output<String>,
    pub plugin_download_url: Option<pulumi::Output<String>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.name;
            inputs.push(("name".to_string(), v.cast()));
        }
        if let Some(v) = self.plugin_download_url {
            inputs.push(("pluginDownloadURL".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:config".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "9.0.0".to_string(),
            plugin_download_url: "http://example.com".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn name(&self) -> pulumi::Output<String> {
        self.resource.output("name").cast()
    }

    pub fn plugin_download_url(&self) -> pulumi::Output<Option<String>> {
        self.resource.output("pluginDownloadURL").cast()
    }

    pub fn version(&self) -> pulumi::Output<String> {
        self.resource.output("version").cast()
    }
}

#[derive(Clone, Debug)]
pub struct GetConfigArgs {
    pub text: pulumi::Output<String>,
}

impl GetConfigArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.text;
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn get_config(ctx: &pulumi::Context, args: GetConfigArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::GetConfigResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "9.0.0".to_string();
    }
    if options.plugin_download_url.is_empty() {
        options.plugin_download_url = "http://example.com".to_string();
    }
    ctx.invoke("config:index:getConfig", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct GetConfigResult {
        pub text: String,
    }

    impl pulumi::FromPropertyValue for GetConfigResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(GetConfigResult {
                text: pulumi::convert::from_property_map(&m, "text")?,
            })
        }
    }
}
