// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("parameterValue", pulumi_subpackage::do_hello_world(&ctx, pulumi_subpackage::DoHelloWorldArgs { input: pulumi::pv::string("goodbye").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("output"));
        Ok(())
    });
}
