// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let parent = pulumi_simple::Resource::new(&ctx, "parent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let alias_urn = pulumi_simple::Resource::new(&ctx, "aliasURN", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let alias_name = pulumi_simple::Resource::new(&ctx, "aliasName", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let alias_no_parent = pulumi_simple::Resource::new(&ctx, "aliasNoParent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let alias_parent = pulumi_simple::Resource::new(&ctx, "aliasParent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { parent: Some(alias_urn.pulumi_resource().clone()), ..Default::default() });
        let alias_type = pulumi_component::Custom::new(&ctx, "aliasType", pulumi_component::CustomArgs { value: Some(pulumi::ops::to_string(pulumi::pv::string("true")).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
