// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:secret".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "14.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub private: pulumi::Output<String>,
    pub private_array: pulumi::Output<Vec<String>>,
    pub private_data: crate::types::DataArgs,
    pub private_data_array: Vec<crate::types::DataArgs>,
    pub private_data_map: std::collections::BTreeMap<String, crate::types::DataArgs>,
    pub private_map: pulumi::Output<std::collections::BTreeMap<String, String>>,
    pub public: pulumi::Output<String>,
    pub public_data: crate::types::DataArgs,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.private;
            inputs.push(("private".to_string(), v.cast()));
        }
        {
            let v = self.private_array;
            inputs.push(("privateArray".to_string(), v.cast()));
        }
        {
            let v = self.private_data;
            inputs.push(("privateData".to_string(), v.into_output()));
        }
        {
            let v = self.private_data_array;
            inputs.push(("privateDataArray".to_string(), pulumi::output::all(v.into_iter().map(|e| e.into_output()).collect()).cast()));
        }
        {
            let v = self.private_data_map;
            inputs.push(("privateDataMap".to_string(), pulumi::output::object(v.into_iter().map(|(k, e)| (k, e.into_output())).collect())));
        }
        {
            let v = self.private_map;
            inputs.push(("privateMap".to_string(), v.cast()));
        }
        {
            let v = self.public;
            inputs.push(("public".to_string(), v.cast()));
        }
        {
            let v = self.public_data;
            inputs.push(("publicData".to_string(), v.into_output()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "secret:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "14.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn private(&self) -> pulumi::Output<String> {
        self.resource.output("private").cast()
    }

    pub fn private_array(&self) -> pulumi::Output<Vec<String>> {
        self.resource.output("privateArray").cast()
    }

    pub fn private_data(&self) -> pulumi::Output<crate::types::Data> {
        self.resource.output("privateData").cast()
    }

    pub fn private_data_array(&self) -> pulumi::Output<Vec<crate::types::Data>> {
        self.resource.output("privateDataArray").cast()
    }

    pub fn private_data_map(&self) -> pulumi::Output<std::collections::BTreeMap<String, crate::types::Data>> {
        self.resource.output("privateDataMap").cast()
    }

    pub fn private_map(&self) -> pulumi::Output<std::collections::BTreeMap<String, String>> {
        self.resource.output("privateMap").cast()
    }

    pub fn public(&self) -> pulumi::Output<String> {
        self.resource.output("public").cast()
    }

    pub fn public_data(&self) -> pulumi::Output<crate::types::Data> {
        self.resource.output("publicData").cast()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DataArgs {
        pub private: pulumi::Output<String>,
        pub public: pulumi::Output<String>,
    }

    impl DataArgs {
        pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
            {
                let v = self.private;
                inputs.push(("private".to_string(), v.cast()));
            }
            {
                let v = self.public;
                inputs.push(("public".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Data {
        pub private: String,
        pub public: String,
    }

    impl pulumi::FromPropertyValue for Data {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Data {
                private: pulumi::convert::from_property_map(&m, "private")?,
                public: pulumi::convert::from_property_map(&m, "public")?,
            })
        }
    }
}
