// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod first;
mod second;

fn main() {
    pulumi::run(|ctx| async move {
        let (second_untainted, resolve_second_untainted) = pulumi::deferred_output();
        let first = crate::first::First::new(&ctx, "first", crate::first::FirstArgs { input: Some(second_untainted.clone()), pulumi_deferred: vec!["input".to_string()], ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        let second = crate::second::Second::new(&ctx, "second", crate::second::SecondArgs { input: Some(pulumi::ops::to_bool(first.untainted())), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        resolve_second_untainted.resolve(second.untainted());
        let (looping_over_many, resolve_looping_over_many) = pulumi::deferred_output();
        let another = crate::first::First::new(&ctx, "another", crate::first::FirstArgs { input: Some(pulumi::ops::eq(pulumi::pv::join(pulumi::pv::string(""), looping_over_many.clone()), pulumi::pv::string("xyz"))), pulumi_deferred: vec!["input".to_string()], ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        let many = {
        let mut __outputs = Vec::new();
        for __range in pulumi::range_entries(pulumi::pv::number(2.0)).await {
        let __instance = crate::second::Second::new(&ctx, &__range.name("many"), crate::second::SecondArgs { input: Some(pulumi::ops::to_bool(another.untainted())), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        __outputs.push(pulumi::pv::object(vec![("untainted".to_string(), __instance.untainted()), ("tainted".to_string(), __instance.tainted())]));
        }
        pulumi::pv::array(__outputs)
        };
        resolve_looping_over_many.resolve(pulumi::ops::for_array(many.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::ops::cond(__v0.clone().index("untainted"), pulumi::pv::string("a"), pulumi::pv::string("b")) }));
        Ok(())
    });
}
