// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct SecondArgs {
    pub input: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for SecondArgs {
    fn default() -> Self {
        SecondArgs {
            input: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct Second {
    resource: pulumi::Resource,
    untainted: pulumi::Output<pulumi::PropertyValue>,
    tainted: pulumi::Output<pulumi::PropertyValue>,
}

impl Second {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: SecondArgs, options: pulumi::ResourceOptions) -> pulumi::Result<Second> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.input { __inputs.push(("input".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:Second".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
            required: &[],
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let input = args.input.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let second_untainted = pulumi_simple::Resource::new(&ctx, &format!("{}-second-untainted", name), pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, __options.clone());
        let second_tainted = pulumi_simple::Resource::new(&ctx, &format!("{}-second-tainted", name), pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::ops::not(input.clone())).cast()) }, __options.clone());
        let __out_0 = second_untainted.value().cast::<pulumi::PropertyValue>();
        let __out_1 = second_tainted.value().cast::<pulumi::PropertyValue>();
        ctx.register_resource_outputs(&__component, vec![("untainted".to_string(), __out_0.clone()), ("tainted".to_string(), __out_1.clone())]);
        Ok(Second {
            resource: __component,
            untainted: __out_0,
            tainted: __out_1,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn untainted(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.untainted.clone()
    }
    pub fn tainted(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.tainted.clone()
    }
}
