// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct ConversionComponentArgs {
    pub boolean: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub float: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub integer: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub string: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for ConversionComponentArgs {
    fn default() -> Self {
        ConversionComponentArgs {
            boolean: None,
            float: None,
            integer: None,
            string: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct ConversionComponent {
    resource: pulumi::Resource,
    boolean: pulumi::Output<pulumi::PropertyValue>,
    float: pulumi::Output<pulumi::PropertyValue>,
    integer: pulumi::Output<pulumi::PropertyValue>,
    string: pulumi::Output<pulumi::PropertyValue>,
}

impl ConversionComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: ConversionComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<ConversionComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.boolean { __inputs.push(("boolean".to_string(), v.clone())); }
        if let Some(v) = &args.float { __inputs.push(("float".to_string(), v.clone())); }
        if let Some(v) = &args.integer { __inputs.push(("integer".to_string(), v.clone())); }
        if let Some(v) = &args.string { __inputs.push(("string".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:ConversionComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let boolean = args.boolean.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let float = args.float.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let integer = args.integer.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let string = args.string.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let res = pulumi_primitive::Resource::new(&ctx, &format!("{}-res", name), pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(boolean.clone()).cast(), boolean_map: pulumi::pv::object(vec![("fromBool".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true))), ("fromString".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true)))]).cast(), float: pulumi::ops::to_number(float.clone()).cast(), integer: pulumi::ops::to_int(integer.clone()).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(2.0)), pulumi::ops::to_number(pulumi::pv::number(42.0)), pulumi::ops::to_number(pulumi::pv::number(6.5))]).cast(), string: pulumi::ops::to_string(string.clone()).cast() }, __options.clone());
        let __out_0 = res.boolean().cast::<pulumi::PropertyValue>();
        let __out_1 = res.float().cast::<pulumi::PropertyValue>();
        let __out_2 = res.integer().cast::<pulumi::PropertyValue>();
        let __out_3 = res.string().cast::<pulumi::PropertyValue>();
        ctx.register_resource_outputs(&__component, vec![("boolean".to_string(), __out_0.clone()), ("float".to_string(), __out_1.clone()), ("integer".to_string(), __out_2.clone()), ("string".to_string(), __out_3.clone())]);
        Ok(ConversionComponent {
            resource: __component,
            boolean: __out_0,
            float: __out_1,
            integer: __out_2,
            string: __out_3,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn boolean(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.boolean.clone()
    }
    pub fn float(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.float.clone()
    }
    pub fn integer(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.integer.clone()
    }
    pub fn string(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.string.clone()
    }
}
