// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod conversion_component;

fn main() {
    pulumi::run(|ctx| async move {
        let plain_bool = ctx.config().require_bool("plainBool")?;
        let plain_number = ctx.config().require_number("plainNumber")?;
        let plain_integer = ctx.config().require_int("plainInteger")?;
        let plain_string = ctx.config().require_string("plainString")?;
        let plain_numeric_string = ctx.config().require_string("plainNumericString")?;
        let secret_number = pulumi::pv::secret(ctx.config().require_object("secretNumber")?);
        let secret_integer = pulumi::pv::secret(ctx.config().require_object("secretInteger")?);
        let secret_string = pulumi::pv::secret(ctx.config().require_object("secretString")?);
        let secret_numeric_string = pulumi::pv::secret(ctx.config().require_object("secretNumericString")?);
        let plain_values = crate::conversion_component::ConversionComponent::new(&ctx, "plainValues", crate::conversion_component::ConversionComponentArgs { boolean: Some(pulumi::ops::to_bool(plain_string.clone())), float: Some(pulumi::ops::to_number(plain_integer.clone())), integer: Some(pulumi::ops::to_int(plain_numeric_string.clone())), string: Some(pulumi::ops::to_string(plain_number.clone())), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        let secret_values = crate::conversion_component::ConversionComponent::new(&ctx, "secretValues", crate::conversion_component::ConversionComponentArgs { boolean: Some(pulumi::ops::to_bool(secret_string.clone())), float: Some(pulumi::ops::to_number(secret_integer.clone())), integer: Some(pulumi::ops::to_int(secret_numeric_string.clone())), string: Some(pulumi::ops::to_string(secret_number.clone())), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        Ok(())
    });
}
