// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prefix = ctx.config().require_string("prefix")?;
        let item = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(pulumi::pv::number(2.0)).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("item"), pulumi_nestedobject::TargetArgs { name: pulumi::ops::to_string(pulumi::pv::concat(vec![prefix.clone(), pulumi::pv::string("-"), __range_scope.clone().index("value")])).cast() }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        Ok(())
    });
}
