// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let num_items = ctx.config().require_int("numItems")?;
        let item_list = ctx.config().require_object("itemList")?;
        let num_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(num_items.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("numResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![pulumi::pv::string("num-"), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let num_target = pulumi_nestedobject::Target::new(&ctx, "numTarget", pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![num_resource.get("0").expect("missing instance of num_resource").name().cast::<pulumi::PropertyValue>(), pulumi::pv::string("+")])).cast()) }, pulumi::ResourceOptions::default());
        let list_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(item_list.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("listResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![__range_scope.clone().index("key"), pulumi::pv::string(":"), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let list_target = pulumi_nestedobject::Target::new(&ctx, "listTarget", pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![list_resource.get("1").expect("missing instance of list_resource").name().cast::<pulumi::PropertyValue>(), pulumi::pv::string("+")])).cast()) }, pulumi::ResourceOptions::default());
        let list_dyn_target = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(item_list.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("listDynTarget"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![list_resource.get(&__range.key_string()).expect("missing instance of list_resource").name().cast::<pulumi::PropertyValue>(), pulumi::pv::string("!")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        Ok(())
    });
}
