// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let greeting = pulumi_myext::Greeting::new(&ctx, "greeting", pulumi_myext::GreetingArgs {  }, pulumi::ResourceOptions::default());
        let greeting_comp = pulumi_myext::GreetingComponent::new(&ctx, "greetingComp", pulumi_myext::GreetingComponentArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue", greeting.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("parameterValueFromComponent", greeting_comp.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("invokeGreeting", pulumi_myext::greet(&ctx, pulumi_myext::GreetArgs { name: Some(pulumi::pv::string("Pulumi").cast()) }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("greeting"));
        Ok(())
    });
}
