// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let greeting = pulumi_extbase::Greeting::new(&ctx, "greeting", pulumi_extbase::GreetingArgs {  }, pulumi::ResourceOptions::default());
        let greeting_comp = pulumi_extbase::GreetingComponent::new(&ctx, "greetingComp", pulumi_extbase::GreetingComponentArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue", greeting.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("parameterValueFromComponent", greeting_comp.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("invokeGreeting", pulumi_extbase::greet(&ctx, pulumi_extbase::GreetArgs { name: pulumi::pv::string("Pulumi").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("greeting"));
        Ok(())
    });
}
