// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prov = pulumi_goodbye::Provider::new(&ctx, "prov", pulumi_goodbye::ProviderArgs { text: Some(pulumi::ops::to_string(pulumi::pv::string("World")).cast()) }, pulumi::ResourceOptions::default());
        let res = pulumi_goodbye::Goodbye::new(&ctx, "res", pulumi_goodbye::GoodbyeArgs {  }, pulumi::ResourceOptions { provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        ctx.export("parameterValue", res.parameter_value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
