// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let hook_test_file = ctx.config().require_string("hookTestFile")?;
        let retry_hook = ctx.register_error_hook("retryHook", { let hook_test_file = hook_test_file.clone(); move |__args| { pulumi::pv::array(vec![pulumi::pv::string("touch"), hook_test_file.clone()]) } }).await?;
        let res = pulumi_flaky::FlakyCreate::new(&ctx, "res", pulumi_flaky::FlakyCreateArgs {  }, pulumi::ResourceOptions { hooks: pulumi::ResourceHookBinding { on_error: vec![retry_hook.clone()], ..Default::default() }, ..Default::default() });
        Ok(())
    });
}
