// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct KeywordComponentArgs {
    pub input: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for KeywordComponentArgs {
    fn default() -> Self {
        KeywordComponentArgs {
            input: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct KeywordComponent {
    resource: pulumi::Resource,
    result: pulumi::Output<pulumi::PropertyValue>,
}

impl KeywordComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: KeywordComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<KeywordComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.input { __inputs.push(("input".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:KeywordComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
            required: &[],
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let input = args.input.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let this = pulumi_simple::Resource::new(&ctx, &format!("{}-this", name), pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(input.clone()).cast()) }, __options.clone());
        let parent = pulumi_simple::Resource::new(&ctx, &format!("{}-parent", name), pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(this.value().cast::<pulumi::PropertyValue>()).cast()) }, __options.clone());
        let __out_0 = parent.value().cast::<pulumi::PropertyValue>();
        ctx.register_resource_outputs(&__component, vec![("result".to_string(), __out_0.clone())]);
        Ok(KeywordComponent {
            resource: __component,
            result: __out_0,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn result(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.result.clone()
    }
}
