// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod keyword_component;

fn main() {
    pulumi::run(|ctx| async move {
        let comp = crate::keyword_component::KeywordComponent::new(&ctx, "comp", crate::keyword_component::KeywordComponentArgs { input: Some(pulumi::pv::bool(true)), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        ctx.export("result", comp.result());
        Ok(())
    });
}
