// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
    pub text: Option<pulumi::Output<std::string::String>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.text {
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:subpackage".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug, Default)]
pub struct HelloWorldArgs {
}

impl HelloWorldArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct HelloWorld {
    resource: pulumi::Resource,
}

impl HelloWorld {
    pub fn new(ctx: &pulumi::Context, name: &str, args: HelloWorldArgs, options: pulumi::ResourceOptions) -> HelloWorld {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "subpackage:index:HelloWorld".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        HelloWorld { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct HelloWorldComponentArgs {
}

impl HelloWorldComponentArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct HelloWorldComponent {
    resource: pulumi::Resource,
}

impl HelloWorldComponent {
    pub fn new(ctx: &pulumi::Context, name: &str, args: HelloWorldComponentArgs, options: pulumi::ResourceOptions) -> HelloWorldComponent {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "subpackage:index:HelloWorldComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        HelloWorldComponent { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug)]
pub struct DoHelloWorldArgs {
    pub input: pulumi::Output<std::string::String>,
}

impl DoHelloWorldArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.input;
            inputs.push(("input".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn do_hello_world(ctx: &pulumi::Context, args: DoHelloWorldArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::DoHelloWorldResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "2.0.0".to_string();
    }
    ctx.invoke("subpackage:index:doHelloWorld", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DoHelloWorldResult {
        pub output: std::string::String,
    }

    impl pulumi::FromPropertyValue for DoHelloWorldResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(DoHelloWorldResult {
                output: pulumi::convert::from_property_map(&m, "output")?,
            })
        }
    }
}
