// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let example = pulumi_subpackage::HelloWorld::new(&ctx, "example", pulumi_subpackage::HelloWorldArgs {  }, pulumi::ResourceOptions::default());
        let example_component = pulumi_subpackage::HelloWorldComponent::new(&ctx, "exampleComponent", pulumi_subpackage::HelloWorldComponentArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue", example.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("parameterValueFromComponent", example_component.parameter_value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
