// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let with_ignore_changes = pulumi_conformance_component::Simple::new(&ctx, "withIgnoreChanges", pulumi_conformance_component::SimpleArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { ignore_changes: vec!["value".to_string()], ..Default::default() });
        let without_ignore_changes = pulumi_conformance_component::Simple::new(&ctx, "withoutIgnoreChanges", pulumi_conformance_component::SimpleArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let simple_resource = pulumi_simple::Resource::new(&ctx, "simpleResource", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(false)).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
