// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct InvokeComponentArgs {
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for InvokeComponentArgs {
    fn default() -> Self {
        InvokeComponentArgs {
            pulumi_deferred: vec![],
        }
    }
}

pub struct InvokeComponent {
    resource: pulumi::Resource,
    result: pulumi::Output<pulumi::PropertyValue>,
}

impl InvokeComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: InvokeComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<InvokeComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:InvokeComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let greeting = pulumi_multi_argument_invoke::multi_argument_invoke(&ctx, pulumi_multi_argument_invoke::MultiArgumentInvokeArgs { first: Some(pulumi::pv::string("hello").cast()), ..Default::default() }, pulumi::InvokeOptions { parent: Some(__component.clone()), ..Default::default() }).cast::<pulumi::PropertyValue>();
        let provider_config = pulumi_config::get_config(&ctx, pulumi_config::GetConfigArgs { text: Some(pulumi::ops::to_string(greeting.clone().index("result")).cast()) }, pulumi::InvokeOptions { parent: Some(__component.clone()), ..Default::default() }).cast::<pulumi::PropertyValue>();
        let __out_0 = provider_config.clone().index("text");
        ctx.register_resource_outputs(&__component, vec![("result".to_string(), __out_0.clone())]);
        Ok(InvokeComponent {
            resource: __component,
            result: __out_0,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn result(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.result.clone()
    }
}
