// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let parent = pulumi_simple::Resource::new(&ctx, "parent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let alias_urn = pulumi_simple::Resource::new(&ctx, "aliasURN", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { parent: Some(parent.pulumi_resource().clone()), aliases: vec![pulumi::Alias::Urn("urn:pulumi:test::l2-resource-option-alias::simple:index:Resource::aliasURN".to_string())], ..Default::default() });
        let alias_new_name = pulumi_simple::Resource::new(&ctx, "aliasNewName", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { aliases: vec![pulumi::Alias::Spec(pulumi::AliasSpec { name: Some("aliasName".to_string()), ..Default::default() })], ..Default::default() });
        let alias_no_parent = pulumi_simple::Resource::new(&ctx, "aliasNoParent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { parent: Some(parent.pulumi_resource().clone()), aliases: vec![pulumi::Alias::Spec(pulumi::AliasSpec { parent: Some(pulumi::AliasParent::None), ..Default::default() })], ..Default::default() });
        let alias_parent = pulumi_simple::Resource::new(&ctx, "aliasParent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { parent: Some(parent.pulumi_resource().clone()), aliases: vec![pulumi::Alias::Spec(pulumi::AliasSpec { parent: Some(pulumi::AliasParent::Urn(alias_urn.pulumi_resource().clone())), ..Default::default() })], ..Default::default() });
        let alias_type = pulumi_simple::Resource::new(&ctx, "aliasType", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { aliases: vec![pulumi::Alias::Spec(pulumi::AliasSpec { type_: Some("component:index:Custom".to_string()), ..Default::default() })], ..Default::default() });
        Ok(())
    });
}
