// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_builtin_info_component::BuiltinInfo::new(&ctx, "res", pulumi_builtin_info_component::BuiltinInfoArgs {  }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
