// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let first_resource = pulumi_keywords::SomeResource::new(&ctx, "firstResource", pulumi_keywords::SomeResourceArgs { builtins: pulumi::pv::string("builtins").cast(), lambda: pulumi::pv::string("lambda").cast(), property: pulumi::pv::string("property").cast() }, pulumi::ResourceOptions::default());
        let second_resource = pulumi_keywords::SomeResource::new(&ctx, "secondResource", pulumi_keywords::SomeResourceArgs { builtins: first_resource.builtins().cast::<pulumi::PropertyValue>().cast(), lambda: first_resource.lambda().cast::<pulumi::PropertyValue>().cast(), property: first_resource.property().cast::<pulumi::PropertyValue>().cast() }, pulumi::ResourceOptions::default());
        let lambda_module_resource = pulumi_keywords::lambda::SomeResource::new(&ctx, "lambdaModuleResource", pulumi_keywords::lambda::SomeResourceArgs { builtins: pulumi::pv::string("builtins").cast(), lambda: pulumi::pv::string("lambda").cast(), property: pulumi::pv::string("property").cast() }, pulumi::ResourceOptions::default());
        let lambda_resource = pulumi_keywords::module::Lambda::new(&ctx, "lambdaResource", pulumi_keywords::module::LambdaArgs { builtins: pulumi::pv::string("builtins").cast(), lambda: pulumi::pv::string("lambda").cast(), property: pulumi::pv::string("property").cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
