// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct GoodbyeArgs {
}

impl GoodbyeArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Goodbye {
    resource: pulumi::Resource,
}

impl Goodbye {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GoodbyeArgs, options: pulumi::ResourceOptions) -> Goodbye {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "goodbye:index:Goodbye".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Goodbye { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn parameter_value(&self) -> pulumi::Output<String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct GoodbyeComponentArgs {
}

impl GoodbyeComponentArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct GoodbyeComponent {
    resource: pulumi::Resource,
}

impl GoodbyeComponent {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GoodbyeComponentArgs, options: pulumi::ResourceOptions) -> GoodbyeComponent {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "goodbye:index:GoodbyeComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        GoodbyeComponent { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn parameter_value(&self) -> pulumi::Output<String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
    pub text: Option<pulumi::Output<String>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        if let Some(v) = self.text {
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:goodbye".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct DoGoodbyeArgs {
    pub input: pulumi::Output<String>,
}

impl DoGoodbyeArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        {
            let v = self.input;
            inputs.push(("input".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn do_goodbye(ctx: &pulumi::Context, args: DoGoodbyeArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::DoGoodbyeResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "2.0.0".to_string();
    }
    ctx.invoke("goodbye:index:doGoodbye", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DoGoodbyeResult {
        pub output: String,
    }

    impl pulumi::FromPropertyValue for DoGoodbyeResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(DoGoodbyeResult {
                output: pulumi::convert::from_property_map(&m, "output")?,
            })
        }
    }
}
