// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let parent = pulumi_simple::Resource::new(&ctx, "parent", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let res = pulumi_conformance_component::Simple::new(&ctx, "res", pulumi_conformance_component::SimpleArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions { parent: Some(parent.pulumi_resource().clone()), aliases: vec![pulumi::Alias::Spec(pulumi::AliasSpec { parent: Some(pulumi::AliasParent::None), ..Default::default() })], ..Default::default() });
        let simple_resource = pulumi_simple::Resource::new(&ctx, "simpleResource", pulumi_simple::ResourceArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(false)).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
