// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let plain_number_array = ctx.config().require_object("plainNumberArray")?;
        let plain_boolean_map = ctx.config().require_object("plainBooleanMap")?;
        let secret_number_array = pulumi::pv::secret(ctx.config().require_object("secretNumberArray")?);
        let secret_boolean_map = pulumi::pv::secret(ctx.config().require_object("secretBooleanMap")?);
        let plain = pulumi_primitive::Resource::new(&ctx, "plain", pulumi_primitive::ResourceArgs { boolean: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), boolean_map: Some(plain_boolean_map.clone().cast()), float: Some(pulumi::ops::to_number(pulumi::pv::number(3.5)).cast()), integer: Some(pulumi::ops::to_int(pulumi::pv::number(3.0)).cast()), number_array: Some(plain_number_array.clone().cast()), string: Some(pulumi::ops::to_string(pulumi::pv::string("plain")).cast()) }, pulumi::ResourceOptions::default());
        let secret = pulumi_primitive::Resource::new(&ctx, "secret", pulumi_primitive::ResourceArgs { boolean: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), boolean_map: Some(secret_boolean_map.clone().cast()), float: Some(pulumi::ops::to_number(pulumi::pv::number(3.5)).cast()), integer: Some(pulumi::ops::to_int(pulumi::pv::number(3.0)).cast()), number_array: Some(secret_number_array.clone().cast()), string: Some(pulumi::ops::to_string(pulumi::pv::string("secret")).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
