// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let num_items = ctx.config().require_int("numItems")?;
        let item_list = ctx.config().require_object("itemList")?;
        let item_map = ctx.config().require_object("itemMap")?;
        let create_bool = ctx.config().require_bool("createBool")?;
        let num_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(num_items.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("numResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![pulumi::pv::string("num-"), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let list_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(item_list.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("listResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![__range_scope.clone().index("key"), pulumi::pv::string(":"), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let map_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(item_map.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("mapResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![__range_scope.clone().index("key"), pulumi::pv::string("="), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let bool_resource = {
        let mut __instance = None;
        for __range in pulumi::range_entries(create_bool.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instance = Some(pulumi_nestedobject::Target::new(&ctx, &__range.name("boolResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::string("bool-resource")).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instance
        };
        Ok(())
    });
}
