// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let create_timeout = ctx.config().require_string("createTimeout")?;
        let no_timeouts = pulumi_simple::Resource::new(&ctx, "noTimeouts", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let create_only = pulumi_simple::Resource::new(&ctx, "createOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: "5m".to_string(), ..Default::default() }), ..Default::default() });
        let update_only = pulumi_simple::Resource::new(&ctx, "updateOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { update: "10m".to_string(), ..Default::default() }), ..Default::default() });
        let delete_only = pulumi_simple::Resource::new(&ctx, "deleteOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { delete: "3m".to_string(), ..Default::default() }), ..Default::default() });
        let read_only = pulumi_simple::Resource::new(&ctx, "readOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { read: "9m".to_string(), ..Default::default() }), ..Default::default() });
        let all_timeouts = pulumi_simple::Resource::new(&ctx, "allTimeouts", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: "2m".to_string(), update: "4m".to_string(), delete: "1m".to_string(), read: "5m".to_string(), ..Default::default() }), ..Default::default() });
        let config_timeout = pulumi_simple::Resource::new(&ctx, "configTimeout", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: "createTimeout".to_string(), ..Default::default() }), ..Default::default() });
        Ok(())
    });
}
