// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let example1 = pulumi_hipackage::HelloWorld::new(&ctx, "example1", pulumi_hipackage::HelloWorldArgs {  }, pulumi::ResourceOptions::default());
        let example_component1 = pulumi_hipackage::HelloWorldComponent::new(&ctx, "exampleComponent1", pulumi_hipackage::HelloWorldComponentArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue1", example1.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("parameterValueFromComponent1", example_component1.parameter_value().cast::<pulumi::PropertyValue>());
        let example2 = pulumi_byepackage::GoodbyeWorld::new(&ctx, "example2", pulumi_byepackage::GoodbyeWorldArgs {  }, pulumi::ResourceOptions::default());
        let example_component2 = pulumi_byepackage::GoodbyeWorldComponent::new(&ctx, "exampleComponent2", pulumi_byepackage::GoodbyeWorldComponentArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue2", example2.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("parameterValueFromComponent2", example_component2.parameter_value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
