// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod primitive_component;

fn main() {
    pulumi::run(|ctx| async move {
        let plain_bool = ctx.config().require_bool("plainBool")?;
        let plain_number = ctx.config().require_number("plainNumber")?;
        let plain_integer = ctx.config().require_int("plainInteger")?;
        let plain_string = ctx.config().require_string("plainString")?;
        let secret_bool = pulumi::pv::secret(ctx.config().require_object("secretBool")?);
        let secret_number = pulumi::pv::secret(ctx.config().require_object("secretNumber")?);
        let secret_integer = pulumi::pv::secret(ctx.config().require_object("secretInteger")?);
        let secret_string = pulumi::pv::secret(ctx.config().require_object("secretString")?);
        let plain = crate::primitive_component::PrimitiveComponent::new(&ctx, "plain", crate::primitive_component::PrimitiveComponentArgs { boolean: Some(plain_bool.clone()), float: Some(plain_number.clone()), integer: Some(plain_integer.clone()), string: Some(plain_string.clone()), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        let secret = crate::primitive_component::PrimitiveComponent::new(&ctx, "secret", crate::primitive_component::PrimitiveComponentArgs { boolean: Some(secret_bool.clone()), float: Some(secret_number.clone()), integer: Some(secret_integer.clone()), string: Some(secret_string.clone()), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        Ok(())
    });
}
