// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let failing_hook = ctx.register_resource_hook("failingHook", false, true, move |__args| { pulumi::pv::array(vec![pulumi::pv::string("false")]) }).await?;
        let res = pulumi_simple::Resource::new(&ctx, "res", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { hooks: pulumi::ResourceHookBinding { after_create: vec![failing_hook.clone()], ..Default::default() }, ..Default::default() });
        Ok(())
    });
}
