// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prov = pulumi_simple::Provider::new(&ctx, "prov", pulumi_simple::ProviderArgs {  }, pulumi::ResourceOptions { env_var_mappings: vec![("MY_VAR".to_string(), "PROVIDER_VAR".to_string()), ("OTHER_VAR".to_string(), "TARGET_VAR".to_string())], ..Default::default() });
        Ok(())
    });
}
