// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod converted;

fn main() {
    pulumi::run(|ctx| async move {
        let direct = pulumi_primitive::Resource::new(&ctx, "direct", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast(), boolean_map: pulumi::pv::object(vec![("t".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true))), ("f".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(false)))]).cast(), float: pulumi::ops::to_number(pulumi::pv::number(3.14)).cast(), integer: pulumi::ops::to_int(pulumi::pv::number(42.0)).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(-1.0)), pulumi::ops::to_number(pulumi::pv::number(0.0)), pulumi::ops::to_number(pulumi::pv::number(1.0))]).cast(), string: pulumi::ops::to_string(pulumi::pv::string("false")).cast() }, pulumi::ResourceOptions::default());
        let converted = crate::converted::Converted::new(&ctx, "converted", crate::converted::ConvertedArgs { boolean: Some(pulumi::pv::bool(false)), float: Some(pulumi::pv::number(2.5)), integer: Some(pulumi::pv::number(7.0)), string: Some(pulumi::pv::string("true")), number_array: Some(pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(10.0)), pulumi::ops::to_number(pulumi::pv::number(11.0))])), boolean_map: Some(pulumi::pv::object(vec![("left".to_string(), pulumi::pv::bool(true)), ("right".to_string(), pulumi::pv::bool(false))])), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        Ok(())
    });
}
