// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ComponentArgs {
    pub resource: Option<pulumi::PropertyValue>,
    pub resource_list: Option<std::vec::Vec<pulumi::PropertyValue>>,
    pub resource_map: Option<std::collections::BTreeMap<std::string::String, pulumi::PropertyValue>>,
}

impl ComponentArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.resource {
            inputs.push(("resource".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
        }
        if let Some(v) = self.resource_list {
            inputs.push(("resourceList".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
        }
        if let Some(v) = self.resource_map {
            inputs.push(("resourceMap".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Component {
    resource: pulumi::Resource,
}

impl Component {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentArgs, options: pulumi::ResourceOptions) -> Component {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component-property-deps:index:Component".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "1.33.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: None,
            deferred_inputs: vec![],
        });
        Component { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn property_deps(&self) -> pulumi::Output<std::collections::BTreeMap<std::string::String, std::vec::Vec<std::string::String>>> {
        self.resource.output("propertyDeps").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct CustomArgs {
    pub value: Option<pulumi::Output<std::string::String>>,
}

impl CustomArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.value {
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Custom {
    resource: pulumi::Resource,
}

impl Custom {
    pub fn new(ctx: &pulumi::Context, name: &str, args: CustomArgs, options: pulumi::ResourceOptions) -> Custom {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component-property-deps:index:Custom".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.33.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: None,
            deferred_inputs: vec![],
        });
        Custom { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:component-property-deps".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.33.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: None,
            deferred_inputs: vec![],
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

