// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod provider_component;

fn main() {
    pulumi::run(|ctx| async move {
        let my_component = crate::provider_component::ProviderComponent::new(&ctx, "myComponent", crate::provider_component::ProviderComponentArgs { text: Some(pulumi::pv::string("hello")), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        ctx.export("result", my_component.result());
        Ok(())
    });
}
