// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct ProviderComponentArgs {
    pub text: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for ProviderComponentArgs {
    fn default() -> Self {
        ProviderComponentArgs {
            text: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct ProviderComponent {
    resource: pulumi::Resource,
    result: pulumi::Output<pulumi::PropertyValue>,
}

impl ProviderComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: ProviderComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<ProviderComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.text { __inputs.push(("text".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:ProviderComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let text = args.text.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let prov = pulumi_config::Provider::new(&ctx, &format!("{}-prov", name), pulumi_config::ProviderArgs { name: Some(pulumi::ops::to_string(pulumi::pv::string("my config")).cast()), ..Default::default() }, __options.clone());
        let res = pulumi_config::Resource::new(&ctx, &format!("{}-res", name), pulumi_config::ResourceArgs { text: Some(pulumi::ops::to_string(text.clone()).cast()) }, pulumi::ResourceOptions { parent: Some(__component.clone()), provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        let __out_0 = res.text().cast::<pulumi::PropertyValue>();
        ctx.register_resource_outputs(&__component, vec![("result".to_string(), __out_0.clone())]);
        Ok(ProviderComponent {
            resource: __component,
            result: __out_0,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn result(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.result.clone()
    }
}
