// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let component_res = pulumi_component::ComponentCustomRefOutput::new(&ctx, "componentRes", pulumi_component::ComponentCustomRefOutputArgs { value: Some(pulumi::ops::to_string(pulumi::pv::string("foo-bar-baz")).cast()) }, pulumi::ResourceOptions::default());
        let res = pulumi_namespaced::Resource::new(&ctx, "res", pulumi_namespaced::ResourceArgs { resource_ref: Some(component_res.r#ref().cast::<pulumi::PropertyValue>().cast()), value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
