// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:index-mod".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "35.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }
}

pub mod index_mine {
    #[derive(Clone, Debug)]
    pub struct ResourceArgs {
        pub text: pulumi::Output<String>,
    }

    impl ResourceArgs {
        pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
            {
                let v = self.text;
                inputs.push(("text".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    pub struct Resource {
        resource: pulumi::Resource,
    }

    impl Resource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "index-mod:indexMine:Resource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "35.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Resource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<String> {
            self.resource.id()
        }

        pub fn text(&self) -> pulumi::Output<String> {
            self.resource.output("text").cast()
        }
    }

    #[derive(Clone, Debug)]
    pub struct ConcatWorldArgs {
        pub value: pulumi::Output<String>,
    }

    impl ConcatWorldArgs {
        pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    pub fn concat_world(ctx: &pulumi::Context, args: ConcatWorldArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::IndexMineConcatWorldResult> {
        let mut options = options;
        if options.version.is_empty() {
            options.version = "35.0.0".to_string();
        }
        ctx.invoke("index-mod:indexMine:concatWorld", args.into_inputs(), options).cast()
    }
}

pub mod index_mine_nested {
    #[derive(Clone, Debug)]
    pub struct ResourceArgs {
        pub text: pulumi::Output<String>,
    }

    impl ResourceArgs {
        pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
            {
                let v = self.text;
                inputs.push(("text".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    pub struct Resource {
        resource: pulumi::Resource,
    }

    impl Resource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "index-mod:indexMine/nested:Resource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "35.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Resource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<String> {
            self.resource.id()
        }

        pub fn text(&self) -> pulumi::Output<String> {
            self.resource.output("text").cast()
        }
    }

    #[derive(Clone, Debug)]
    pub struct ConcatWorldArgs {
        pub value: pulumi::Output<String>,
    }

    impl ConcatWorldArgs {
        pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    pub fn concat_world(ctx: &pulumi::Context, args: ConcatWorldArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::IndexMineNestedConcatWorldResult> {
        let mut options = options;
        if options.version.is_empty() {
            options.version = "35.0.0".to_string();
        }
        ctx.invoke("index-mod:indexMine/nested:concatWorld", args.into_inputs(), options).cast()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct IndexMineNestedConcatWorldResult {
        pub result: String,
    }

    impl pulumi::FromPropertyValue for IndexMineNestedConcatWorldResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(IndexMineNestedConcatWorldResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct IndexMineConcatWorldResult {
        pub result: String,
    }

    impl pulumi::FromPropertyValue for IndexMineConcatWorldResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(IndexMineConcatWorldResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }
}
