// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct BuiltinInfoArgs {
}

impl BuiltinInfoArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct BuiltinInfo {
    resource: pulumi::Resource,
}

impl BuiltinInfo {
    pub fn new(ctx: &pulumi::Context, name: &str, args: BuiltinInfoArgs, options: pulumi::ResourceOptions) -> BuiltinInfo {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "builtin-info-component:index:BuiltinInfo".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "37.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: None,
            deferred_inputs: vec![],
        });
        BuiltinInfo { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn is_dry_run(&self) -> pulumi::Output<Option<bool>> {
        self.resource.output("isDryRun").cast()
    }

    pub fn organization(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("organization").cast()
    }

    pub fn project(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("project").cast()
    }

    pub fn stack(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("stack").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:builtin-info-component".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "37.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: None,
            deferred_inputs: vec![],
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

