// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let greeting = pulumi_extbase::Greeting::new(&ctx, "greeting", pulumi_extbase::GreetingArgs {  }, pulumi::ResourceOptions::default());
        let base = pulumi_extbase::Base::new(&ctx, "base", pulumi_extbase::BaseArgs {  }, pulumi::ResourceOptions::default());
        ctx.export("parameterValue", greeting.parameter_value().cast::<pulumi::PropertyValue>());
        ctx.export("baseValue", base.base_value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
