// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let item_map = ctx.config().require_object("itemMap")?;
        let map_resource = {
        let mut __instances = std::collections::BTreeMap::new();
        for __range in pulumi::range_entries(item_map.clone()).await {
        let __range_scope = pulumi::pv::object(vec![("key".to_string(), pulumi::Output::from_value(__range.key.clone())), ("value".to_string(), pulumi::Output::from_value(__range.value.clone()))]);
        __instances.insert(__range.key_string(), pulumi_nestedobject::Target::new(&ctx, &__range.name("mapResource"), pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![__range_scope.clone().index("key"), pulumi::pv::string("="), __range_scope.clone().index("value")])).cast()) }, pulumi::ResourceOptions::default()));
        }
        __instances
        };
        let map_target = pulumi_nestedobject::Target::new(&ctx, "mapTarget", pulumi_nestedobject::TargetArgs { name: Some(pulumi::ops::to_string(pulumi::pv::concat(vec![map_resource.get("k1").expect("missing instance of map_resource").name().cast::<pulumi::PropertyValue>(), pulumi::pv::string("+")])).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
