// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct BaseArgs {
}

impl BaseArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Base {
    resource: pulumi::Resource,
}

impl Base {
    pub fn new(ctx: &pulumi::Context, name: &str, args: BaseArgs, options: pulumi::ResourceOptions) -> Base {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "extbase:index:Base".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "45.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Base { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }

    pub fn base_value(&self) -> pulumi::Output<String> {
        self.resource.output("baseValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> Vec<(String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:extbase".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "45.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<String> {
        self.resource.id()
    }
}

