// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_plain::Resource::new(&ctx, "res", pulumi_plain::ResourceArgs { data: Some(pulumi_plain::types::DataArgs { bool_array: Some(vec![true, false]), boolean: Some(true), float: Some(4.5), inner_data: Some(pulumi_plain::types::InnerDataArgs { bool_array: Some(vec![false, true]), boolean: Some(false), float: Some(2.17), integer: Some(-12), string: Some("Goodbye".to_string()), string_map: Some(std::collections::BTreeMap::from([("two".to_string(), "turtle doves".to_string()), ("three".to_string(), "french hens".to_string())])) }), integer: Some(1024), string: Some("Hello".to_string()), string_map: Some(std::collections::BTreeMap::from([("x".to_string(), "100".to_string()), ("y".to_string(), "200".to_string())])) }), data_list: Some(vec![pulumi_plain::types::InnerDataArgs { bool_array: Some(vec![true]), boolean: Some(true), float: Some(3.14), integer: Some(42), string: Some("Plain".to_string()), string_map: Some(std::collections::BTreeMap::from([("one".to_string(), "partridge".to_string())])) }]), ..Default::default() }, pulumi::ResourceOptions::default());
        let empty_list_res = pulumi_plain::Resource::new(&ctx, "emptyListRes", pulumi_plain::ResourceArgs { data: Some(pulumi_plain::types::DataArgs { bool_array: Some(vec![]), boolean: Some(false), float: Some(0.0), inner_data: Some(pulumi_plain::types::InnerDataArgs { bool_array: Some(vec![]), boolean: Some(false), float: Some(0.0), integer: Some(0), string: Some("".to_string()), string_map: Some(std::collections::BTreeMap::from([])) }), integer: Some(0), string: Some("".to_string()), string_map: Some(std::collections::BTreeMap::from([])) }), data_list: Some(vec![]), ..Default::default() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
