// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let source = pulumi_bytesource::Resource::new(&ctx, "source", pulumi_bytesource::ResourceArgs { base64: Some(pulumi::ops::to_string(pulumi::pv::string("AGhlbGxvIID+/yB3b3JsZPAo")).cast()) }, pulumi::ResourceOptions::default());
        let sink = pulumi_bytesink::Resource::new(&ctx, "sink", pulumi_bytesink::ResourceArgs { bytes: Some(pulumi::ops::to_string(source.bytes().cast::<pulumi::PropertyValue>()).cast()), expect_base64: Some(pulumi::ops::to_string(source.base64().cast::<pulumi::PropertyValue>()).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
