// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res1 = pulumi_module_format::r#mod::Resource::new(&ctx, "res1", pulumi_module_format::r#mod::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::r#mod::concat_world(&ctx, pulumi_module_format::r#mod::ConcatWorldArgs { value: pulumi::pv::string("hello").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out1", ctx.call("module-format:mod_Resource:Resource/call", res1.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("x"))]).index("output"));
        let res2 = pulumi_module_format::r#mod::Resource::new(&ctx, "res2", pulumi_module_format::r#mod::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::r#mod::concat_world(&ctx, pulumi_module_format::r#mod::ConcatWorldArgs { value: pulumi::pv::string("goodbye").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out2", ctx.call("module-format:mod_Resource:Resource/call", res2.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("xx"))]).index("output"));
        let res3 = pulumi_module_format::mod_nested::Resource::new(&ctx, "res3", pulumi_module_format::mod_nested::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::mod_nested::concat_world(&ctx, pulumi_module_format::mod_nested::ConcatWorldArgs { value: pulumi::pv::string("hello").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out3", ctx.call("module-format:mod/nested_Resource:Resource/call", res3.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("x"))]).index("output"));
        let res4 = pulumi_module_format::mod_nested::Resource::new(&ctx, "res4", pulumi_module_format::mod_nested::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::mod_nested::concat_world(&ctx, pulumi_module_format::mod_nested::ConcatWorldArgs { value: pulumi::pv::string("goodbye").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out4", ctx.call("module-format:mod/nested_Resource:Resource/call", res4.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("xx"))]).index("output"));
        let res5 = pulumi_module_format::Resource::new(&ctx, "res5", pulumi_module_format::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::concat_world(&ctx, pulumi_module_format::ConcatWorldArgs { value: pulumi::pv::string("bonjour").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out5", ctx.call("module-format:index_Resource:Resource/call", res5.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("x"))]).index("output"));
        let res6 = pulumi_module_format::Resource::new(&ctx, "res6", pulumi_module_format::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::concat_world(&ctx, pulumi_module_format::ConcatWorldArgs { value: pulumi::pv::string("youkoso").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out6", ctx.call("module-format:index_Resource:Resource/call", res6.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("xx"))]).index("output"));
        let res7 = pulumi_module_format::Resource::new(&ctx, "res7", pulumi_module_format::ResourceArgs { text: pulumi::ops::to_string(pulumi_module_format::concat_world(&ctx, pulumi_module_format::ConcatWorldArgs { value: pulumi::pv::string("guten tag").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out7", ctx.call("module-format:index_Resource:Resource/call", res7.pulumi_resource(), vec![("input".to_string(), pulumi::pv::string("xxx"))]).index("output"));
        Ok(())
    });
}
