// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct LocalArgs {
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for LocalArgs {
    fn default() -> Self {
        LocalArgs {
            pulumi_deferred: vec![],
        }
    }
}

pub struct Local {
    resource: pulumi::Resource,
    result: pulumi::Output<pulumi::PropertyValue>,
}

impl Local {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: LocalArgs, options: pulumi::ResourceOptions) -> pulumi::Result<Local> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:Local".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let mlc = pulumi_component::ComponentForeignChild::new(&ctx, &format!("{}-mlc", name), pulumi_component::ComponentForeignChildArgs { value: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, __options.clone());
        let __out_0 = mlc.value().cast::<pulumi::PropertyValue>();
        ctx.register_resource_outputs(&__component, vec![("result".to_string(), __out_0.clone())]);
        Ok(Local {
            resource: __component,
            result: __out_0,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn result(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.result.clone()
    }
}
