// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod local;

fn main() {
    pulumi::run(|ctx| async move {
        let explicit = pulumi_simple::Provider::new(&ctx, "explicit", pulumi_simple::ProviderArgs {  }, pulumi::ResourceOptions::default());
        let with_providers = crate::local::Local::new(&ctx, "withProviders", crate::local::LocalArgs { ..Default::default() }, pulumi::ResourceOptions { providers: vec![("simple".to_string(), explicit.pulumi_resource().clone())], ..Default::default() }).await?;
        ctx.export("result", with_providers.result());
        Ok(())
    });
}
