// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod inner_component;
mod outer_component;

fn main() {
    pulumi::run(|ctx| async move {
        let outer_component = crate::outer_component::OuterComponent::new(&ctx, "outerComponent", crate::outer_component::OuterComponentArgs { input: Some(pulumi::pv::bool(true)), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        ctx.export("result", outer_component.output());
        Ok(())
    });
}
