// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct OuterComponentArgs {
    pub input: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for OuterComponentArgs {
    fn default() -> Self {
        OuterComponentArgs {
            input: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct OuterComponent {
    resource: pulumi::Resource,
    output: pulumi::Output<pulumi::PropertyValue>,
}

impl OuterComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: OuterComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<OuterComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.input { __inputs.push(("input".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:OuterComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
            required: &[],
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let input = args.input.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let inner_component = crate::inner_component::InnerComponent::new(&ctx, &format!("{}-innerComponent", name), crate::inner_component::InnerComponentArgs { input: Some(pulumi::ops::not(input.clone())), ..Default::default() }, __options.clone()).await?;
        let __out_0 = inner_component.output();
        ctx.register_resource_outputs(&__component, vec![("output".to_string(), __out_0.clone())]);
        Ok(OuterComponent {
            resource: __component,
            output: __out_0,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
    pub fn output(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.output.clone()
    }
}
