// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct GoodbyeWorldArgs {
}

impl GoodbyeWorldArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct GoodbyeWorld {
    resource: pulumi::Resource,
}

impl GoodbyeWorld {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GoodbyeWorldArgs, options: pulumi::ResourceOptions) -> GoodbyeWorld {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "byepackage:index:GoodbyeWorld".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: Some(pulumi::PackageDescriptor { base_name: "parameterized".to_string(), base_version: "1.2.3".to_string(), download_url: "".to_string(), name: "byepackage".to_string(), version: "2.0.0".to_string(), base64_parameter: "R29vZGJ5ZVdvcmxk".to_string(), extension: false }),
            deferred_inputs: vec![],
            required: &[],
        });
        GoodbyeWorld { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct GoodbyeWorldComponentArgs {
}

impl GoodbyeWorldComponentArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct GoodbyeWorldComponent {
    resource: pulumi::Resource,
}

impl GoodbyeWorldComponent {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GoodbyeWorldComponentArgs, options: pulumi::ResourceOptions) -> GoodbyeWorldComponent {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "byepackage:index:GoodbyeWorldComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: Some(pulumi::PackageDescriptor { base_name: "parameterized".to_string(), base_version: "1.2.3".to_string(), download_url: "".to_string(), name: "byepackage".to_string(), version: "2.0.0".to_string(), base64_parameter: "R29vZGJ5ZVdvcmxk".to_string(), extension: false }),
            deferred_inputs: vec![],
            required: &[],
        });
        GoodbyeWorldComponent { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
    pub text: Option<pulumi::Output<std::string::String>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.text {
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:byepackage".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: Some(pulumi::PackageDescriptor { base_name: "parameterized".to_string(), base_version: "1.2.3".to_string(), download_url: "".to_string(), name: "byepackage".to_string(), version: "2.0.0".to_string(), base64_parameter: "R29vZGJ5ZVdvcmxk".to_string(), extension: false }),
            deferred_inputs: vec![],
            required: &[],
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug, Default)]
pub struct DoGoodbyeWorldArgs {
    pub input: Option<pulumi::Output<std::string::String>>,
}

impl DoGoodbyeWorldArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.input {
            inputs.push(("input".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn do_goodbye_world(ctx: &pulumi::Context, args: DoGoodbyeWorldArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::DoGoodbyeWorldResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "2.0.0".to_string();
    }
    if options.package.is_none() {
        options.package = Some(pulumi::PackageDescriptor { base_name: "parameterized".to_string(), base_version: "1.2.3".to_string(), download_url: "".to_string(), name: "byepackage".to_string(), version: "2.0.0".to_string(), base64_parameter: "R29vZGJ5ZVdvcmxk".to_string(), extension: false });
    }
    ctx.invoke("byepackage:index:doGoodbyeWorld", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DoGoodbyeWorldResult {
        pub output: std::string::String,
    }

    impl pulumi::FromPropertyValue for DoGoodbyeWorldResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(DoGoodbyeWorldResult {
                output: pulumi::convert::from_property_map(&m, "output")?,
            })
        }
    }
}
