// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let my_stash = pulumi_pulumi::Stash::new(&ctx, "myStash", pulumi_pulumi::StashArgs { input: pulumi::pv::object(vec![("key".to_string(), pulumi::pv::array(vec![pulumi::pv::string("value"), pulumi::pv::string("s")])), ("".to_string(), pulumi::pv::bool(false))]).cast() }, pulumi::ResourceOptions::default());
        ctx.export("stashInput", my_stash.input().cast::<pulumi::PropertyValue>());
        ctx.export("stashOutput", my_stash.output().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
