// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let custom1 = pulumi_component_property_deps::Custom::new(&ctx, "custom1", pulumi_component_property_deps::CustomArgs { value: pulumi::ops::to_string(pulumi::pv::string("hello")).cast() }, pulumi::ResourceOptions::default());
        let custom2 = pulumi_component_property_deps::Custom::new(&ctx, "custom2", pulumi_component_property_deps::CustomArgs { value: pulumi::ops::to_string(pulumi::pv::string("world")).cast() }, pulumi::ResourceOptions::default());
        let component1 = ctx.register_resource(pulumi::RegisterRequest { type_: "component-property-deps:index:Component".to_string(), name: "component1".to_string(), custom: false, remote: true, version: "1.33.7".to_string(), plugin_download_url: "".to_string(), inputs: vec![("resource".to_string(), custom1.pulumi_resource().reference()), ("resourceList".to_string(), pulumi::pv::array(vec![custom1.pulumi_resource().reference(), custom2.pulumi_resource().reference()])), ("resourceMap".to_string(), pulumi::pv::object(vec![("one".to_string(), custom1.pulumi_resource().reference()), ("two".to_string(), custom2.pulumi_resource().reference())]))], options: pulumi::ResourceOptions::default() });
        ctx.export("propertyDepsFromCall", ctx.call("component-property-deps:index:Component/refs", component1.pulumi_resource(), vec![("resource".to_string(), custom1.pulumi_resource().reference()), ("resourceList".to_string(), pulumi::pv::array(vec![custom1.pulumi_resource().reference(), custom2.pulumi_resource().reference()])), ("resourceMap".to_string(), pulumi::pv::object(vec![("one".to_string(), custom1.pulumi_resource().reference()), ("two".to_string(), custom2.pulumi_resource().reference())]))]).index("result"));
        Ok(())
    });
}
