// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct GreetingArgs {
}

impl GreetingArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Greeting {
    resource: pulumi::Resource,
}

impl Greeting {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GreetingArgs, options: pulumi::ResourceOptions) -> Greeting {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "extbase:index:Greeting".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: Some(pulumi::PackageDescriptor { base_name: "extbase".to_string(), base_version: "45.0.0".to_string(), download_url: "".to_string(), name: "myext".to_string(), version: "2.0.0".to_string(), base64_parameter: "SGVsbG8=".to_string(), extension: true }),
            deferred_inputs: vec![],
        });
        Greeting { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct GreetingComponentArgs {
}

impl GreetingComponentArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct GreetingComponent {
    resource: pulumi::Resource,
}

impl GreetingComponent {
    pub fn new(ctx: &pulumi::Context, name: &str, args: GreetingComponentArgs, options: pulumi::ResourceOptions) -> GreetingComponent {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "extbase:index:GreetingComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "2.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
            package: Some(pulumi::PackageDescriptor { base_name: "extbase".to_string(), base_version: "45.0.0".to_string(), download_url: "".to_string(), name: "myext".to_string(), version: "2.0.0".to_string(), base64_parameter: "SGVsbG8=".to_string(), extension: true }),
            deferred_inputs: vec![],
        });
        GreetingComponent { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn parameter_value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("parameterValue").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct GreetArgs {
    pub name: Option<pulumi::Output<std::string::String>>,
}

impl GreetArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.name {
            inputs.push(("name".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn greet(ctx: &pulumi::Context, args: GreetArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::GreetResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "2.0.0".to_string();
    }
    if options.package.is_none() {
        options.package = Some(pulumi::PackageDescriptor { base_name: "extbase".to_string(), base_version: "45.0.0".to_string(), download_url: "".to_string(), name: "myext".to_string(), version: "2.0.0".to_string(), base64_parameter: "SGVsbG8=".to_string(), extension: true });
    }
    ctx.invoke("extbase:index:greet", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct GreetResult {
        pub greeting: std::string::String,
    }

    impl pulumi::FromPropertyValue for GreetResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(GreetResult {
                greeting: pulumi::convert::from_property_map(&m, "greeting")?,
            })
        }
    }
}
