// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_ref_ref::Resource::new(&ctx, "res", pulumi_ref_ref::ResourceArgs { data: pulumi_ref_ref::types::DataArgs { bool_array: pulumi::pv::array(vec![]).cast(), boolean: pulumi::pv::bool(true).cast(), float: pulumi::pv::number(4.5).cast(), inner_data: pulumi_ref_ref::types::InnerDataArgs { bool_array: pulumi::pv::array(vec![pulumi::pv::bool(false), pulumi::pv::bool(true)]).cast(), boolean: pulumi::pv::bool(false).cast(), float: pulumi::pv::number(2.17).cast(), integer: pulumi::pv::number(-12.0).cast(), string: pulumi::pv::string("Goodbye").cast(), string_map: pulumi::pv::object(vec![("two".to_string(), pulumi::pv::string("turtle doves")), ("three".to_string(), pulumi::pv::string("french hens"))]).cast() }, inner_data_list: None, integer: pulumi::pv::number(1024.0).cast(), optional_inner: None, string: pulumi::pv::string("Hello").cast(), string_map: pulumi::pv::object(vec![("x".to_string(), pulumi::pv::string("100")), ("y".to_string(), pulumi::pv::string("200"))]).cast() } }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
