// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let config_grpc_provider = pulumi_config_grpc::Provider::new(&ctx, "config_grpc_provider", pulumi_config_grpc::ProviderArgs { list_secret_string1: Some(pulumi::pv::array(vec![pulumi::ops::to_string(pulumi::pv::string("SECRET")), pulumi::ops::to_string(pulumi::pv::string("SECRET2"))]).cast()), map_secret_string1: Some(pulumi::pv::object(vec![("key1".to_string(), pulumi::ops::to_string(pulumi::pv::string("SECRET"))), ("key2".to_string(), pulumi::ops::to_string(pulumi::pv::string("SECRET2")))]).cast()), obj_secret_string1: Some(pulumi_config_grpc::types::TsecretString1Args { secret_x: Some(pulumi::ops::to_string(pulumi::pv::string("SECRET")).cast()) }), secret_bool1: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), secret_int1: Some(pulumi::ops::to_int(pulumi::pv::number(16.0)).cast()), secret_num1: Some(pulumi::ops::to_number(pulumi::pv::number(123456.789)).cast()), secret_string1: Some(pulumi::ops::to_string(pulumi::pv::string("SECRET")).cast()), ..Default::default() }, pulumi::ResourceOptions::default());
        let config = pulumi_config_grpc::ConfigFetcher::new(&ctx, "config", pulumi_config_grpc::ConfigFetcherArgs {  }, pulumi::ResourceOptions { provider: Some(config_grpc_provider.pulumi_resource().clone()), ..Default::default() });
        Ok(())
    });
}
