// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

mod primitive_component;

fn main() {
    pulumi::run(|ctx| async move {
        let plain_number_array = ctx.config().require_object("plainNumberArray")?;
        let plain_boolean_map = ctx.config().require_object("plainBooleanMap")?;
        let secret_number_array = pulumi::pv::secret(ctx.config().require_object("secretNumberArray")?);
        let secret_boolean_map = pulumi::pv::secret(ctx.config().require_object("secretBooleanMap")?);
        let plain = crate::primitive_component::PrimitiveComponent::new(&ctx, "plain", crate::primitive_component::PrimitiveComponentArgs { number_array: Some(plain_number_array.clone()), boolean_map: Some(plain_boolean_map.clone()), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        let secret = crate::primitive_component::PrimitiveComponent::new(&ctx, "secret", crate::primitive_component::PrimitiveComponentArgs { number_array: Some(secret_number_array.clone()), boolean_map: Some(secret_boolean_map.clone()), ..Default::default() }, pulumi::ResourceOptions::default()).await?;
        Ok(())
    });
}
