// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

pub struct PrimitiveComponentArgs {
    pub number_array: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub boolean_map: Option<pulumi::Output<pulumi::PropertyValue>>,
    /// Inputs supplied by a component that is itself waiting on this
    /// one; they reach the children but are left out of the
    /// component's own registration to break the cycle.
    pub pulumi_deferred: Vec<String>,
}

impl Default for PrimitiveComponentArgs {
    fn default() -> Self {
        PrimitiveComponentArgs {
            number_array: None,
            boolean_map: None,
            pulumi_deferred: vec![],
        }
    }
}

pub struct PrimitiveComponent {
    resource: pulumi::Resource,
}

impl PrimitiveComponent {
    pub async fn new(ctx: &pulumi::Context, name: &str, args: PrimitiveComponentArgs, options: pulumi::ResourceOptions) -> pulumi::Result<PrimitiveComponent> {
        let ctx = pulumi::Context::clone(ctx);
        let mut __inputs: Vec<(String, pulumi::Output<pulumi::PropertyValue>)> = vec![];
        let mut __deferred: Vec<String> = vec![];
        if let Some(v) = &args.number_array { __inputs.push(("numberArray".to_string(), v.clone())); }
        if let Some(v) = &args.boolean_map { __inputs.push(("booleanMap".to_string(), v.clone())); }
        __deferred.extend(args.pulumi_deferred.iter().cloned());
        let __component = ctx.register_resource(pulumi::RegisterRequest {
            type_: "components:index:PrimitiveComponent".to_string(),
            name: name.to_string(),
            custom: false,
            remote: false,
            version: String::new(),
            plugin_download_url: String::new(),
            inputs: __inputs,
            options,
            package: None,
            deferred_inputs: __deferred,
        });
        let __options = pulumi::ResourceOptions { parent: Some(__component.clone()), ..Default::default() };
        let number_array = args.number_array.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let boolean_map = args.boolean_map.clone().unwrap_or_else(|| pulumi::Output::from_value(pulumi::PropertyValue::Null));
        let res = pulumi_primitive::Resource::new(&ctx, &format!("{}-res", name), pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast(), boolean_map: boolean_map.clone().cast(), float: pulumi::ops::to_number(pulumi::pv::number(3.5)).cast(), integer: pulumi::ops::to_int(pulumi::pv::number(3.0)).cast(), number_array: number_array.clone().cast(), string: pulumi::ops::to_string(pulumi::pv::string("plain")).cast() }, __options.clone());
        ctx.register_resource_outputs(&__component, vec![]);
        Ok(PrimitiveComponent {
            resource: __component,
        })
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }
}
